# Generated by Django 3.2.4 on 2021-09-08 04:54

from django.db import migrations, models
import zs_projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=zs_projects.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
