# Generated by Django 3.2.4 on 2021-09-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zs_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='developer',
            field=models.CharField(default='Zahra Safdari', max_length=150),
        ),
    ]
